[package]
name = "calm_io"
version = "0.1.0"
authors = ["myrrlyn <self@myrrlyn.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pipefail]
path = "pipefail"
version = "0.1"

[workspace]
members = [
    "pipefail",
]
