################################################################################
#                                   Justfile                                   #
#                                                                              #
# Set of `filters/` subroutines to execute for development work.               #
################################################################################

publish:
	cargo publish
